import { t, type Dictionary } from "intlayer";

const footerContent = {
  key: "footer",
  content: {
    tagline: t({
      en: "Discover · Explore",
      zh: "发现 · 探索",
      hi: "जानें · घूमें",
      es: "Descubre · Explora",
      fr: "Découvrir · Explorer",
      ar: "اكتشف · استكشف",
      bn: "আবিষ্কার · অন্বেষণ",
      pt: "Descubra · Explore",
      ru: "Открывай · Исследуй",
      ur: "دریافت کریں · تلاش کریں",
      id: "Temukan · Jelajahi",
      de: "Entdecken · Erkunden",
      ja: "発見 · 探検",
      sw: "Gundua · Chunguza",
      ko: "발견 · 탐험",
      it: "Scopri · Esplora",
    }),
    description: t({
      en: "Events, businesses, and destinations — local and international. Powered by smart recommendations tailored to your interests.",
      zh: "本地及国际活动、商家和目的地。由根据你的兴趣量身定制的智能推荐提供支持。",
      hi: "इवेंट्स, व्यवसाय और गंतव्य — स्थानीय और अंतरराष्ट्रीय। आपकी रुचियों के अनुरूप स्मार्ट सिफारिशों द्वारा संचालित।",
      es: "Eventos, negocios y destinos, locales e internacionales. Impulsado por recomendaciones inteligentes adaptadas a tus intereses.",
      fr: "Événements, entreprises et destinations — locaux et internationaux. Propulsé par des recommandations intelligentes adaptées à vos centres d'intérêt.",
      ar: "فعاليات وأعمال ووجهات — محلية ودولية. مدعوم بتوصيات ذكية مصممة خصيصًا لاهتماماتك.",
      bn: "ইভেন্ট, ব্যবসা এবং গন্তব্য — স্থানীয় এবং আন্তর্জাতিক। আপনার আগ্রহ অনুযায়ী স্মার্ট সুপারিশ দ্বারা চালিত।",
      pt: "Eventos, empresas e destinos — locais e internacionais. Com recomendações inteligentes adaptadas aos seus interesses.",
      ru: "События, компании и направления — местные и международные. На основе умных рекомендаций, адаптированных под ваши интересы.",
      ur: "ایونٹس، کاروبار اور منزلیں — مقامی اور بین الاقوامی۔ آپ کی دلچسپیوں کے مطابق ہوشیار تجاویز سے تقویت یافتہ۔",
      id: "Acara, bisnis, dan destinasi — lokal dan internasional. Didukung oleh rekomendasi cerdas yang disesuaikan dengan minat Anda.",
      de: "Veranstaltungen, Unternehmen und Reiseziele — lokal und international. Angetrieben von intelligenten Empfehlungen, die auf deine Interessen zugeschnitten sind.",
      ja: "国内外のイベント、ビジネス、観光地。あなたの興味に合わせたスマートなおすすめ機能を搭載。",
      sw: "Matukio, biashara, na maeneo — ya karibu na kimataifa. Inaendeshwa na mapendekezo mahiri yaliyolengwa kwa mapendeleo yako.",
      ko: "국내외 이벤트, 비즈니스, 여행지. 관심사에 맞춘 스마트 추천 기능 제공.",
      it: "Eventi, attività e destinazioni, locali e internazionali. Basato su consigli intelligenti su misura per i tuoi interessi.",
    }),
    colExplore: t({
      en: "Explore", zh: "探索", hi: "अन्वेषण करें", es: "Explorar", fr: "Explorer", ar: "استكشف",
      bn: "অন্বেষণ", pt: "Explorar", ru: "Исследовать", ur: "دریافت کریں", id: "Jelajahi", de: "Entdecken",
      ja: "探索", sw: "Chunguza", ko: "탐색", it: "Esplora",
    }),
    colCategories: t({
      en: "Categories", zh: "分类", hi: "श्रेणियाँ", es: "Categorías", fr: "Catégories", ar: "الفئات",
      bn: "বিভাগ", pt: "Categorias", ru: "Категории", ur: "زمرہ جات", id: "Kategori", de: "Kategorien",
      ja: "カテゴリー", sw: "Jamii", ko: "카테고리", it: "Categorie",
    }),
    colOrganizers: t({
      en: "Organizers", zh: "组织者", hi: "आयोजक", es: "Organizadores", fr: "Organisateurs", ar: "المنظمون",
      bn: "আয়োজক", pt: "Organizadores", ru: "Организаторы", ur: "منتظمین", id: "Penyelenggara", de: "Veranstalter",
      ja: "主催者", sw: "Waandaaji", ko: "주최자", it: "Organizzatori",
    }),
    linkAllEvents: t({
      en: "All Events", zh: "所有活动", hi: "सभी इवेंट्स", es: "Todos los eventos", fr: "Tous les événements", ar: "جميع الفعاليات",
      bn: "সব ইভেন্ট", pt: "Todos os eventos", ru: "Все события", ur: "تمام ایونٹس", id: "Semua Acara", de: "Alle Veranstaltungen",
      ja: "すべてのイベント", sw: "Matukio Yote", ko: "모든 이벤트", it: "Tutti gli eventi",
    }),
    linkBusinesses: t({
      en: "Businesses", zh: "商家", hi: "व्यवसाय", es: "Negocios", fr: "Entreprises", ar: "الأعمال",
      bn: "ব্যবসা", pt: "Empresas", ru: "Бизнес", ur: "کاروبار", id: "Bisnis", de: "Unternehmen",
      ja: "ビジネス", sw: "Biashara", ko: "비즈니스", it: "Attività",
    }),
    linkDestinations: t({
      en: "Destinations", zh: "目的地", hi: "गंतव्य", es: "Destinos", fr: "Destinations", ar: "الوجهات",
      bn: "গন্তব্য", pt: "Destinos", ru: "Направления", ur: "منزلیں", id: "Destinasi", de: "Reiseziele",
      ja: "観光地", sw: "Maeneo", ko: "여행지", it: "Destinazioni",
    }),
    linkTravelBlog: t({
      en: "Travel Blog", zh: "旅行博客", hi: "यात्रा ब्लॉग", es: "Blog de viajes", fr: "Blog de voyage", ar: "مدونة السفر",
      bn: "ভ্রমণ ব্লগ", pt: "Blog de viagens", ru: "Блог о путешествиях", ur: "سفری بلاگ", id: "Blog Perjalanan", de: "Reiseblog",
      ja: "旅行ブログ", sw: "Blogu ya Safari", ko: "여행 블로그", it: "Blog di viaggio",
    }),
    linkFreeEvents: t({
      en: "Free Events", zh: "免费活动", hi: "मुफ़्त इवेंट्स", es: "Eventos gratuitos", fr: "Événements gratuits", ar: "فعاليات مجانية",
      bn: "বিনামূল্যে ইভেন্ট", pt: "Eventos gratuitos", ru: "Бесплатные события", ur: "مفت ایونٹس", id: "Acara Gratis", de: "Kostenlose Veranstaltungen",
      ja: "無料イベント", sw: "Matukio ya Bure", ko: "무료 이벤트", it: "Eventi gratuiti",
    }),
    linkWildlifeSafari: t({
      en: "Wildlife & Safari", zh: "野生动物与野生动物园", hi: "वन्यजीव और सफारी", es: "Vida silvestre y safari", fr: "Faune et safari", ar: "الحياة البرية والسفاري",
      bn: "বন্যপ্রাণী ও সাফারি", pt: "Vida selvagem e safári", ru: "Дикая природа и сафари", ur: "جنگلی حیات اور سفاری", id: "Satwa Liar & Safari", de: "Tierwelt & Safari",
      ja: "野生動物とサファリ", sw: "Wanyamapori na Safari", ko: "야생동물 & 사파리", it: "Fauna selvatica e safari",
    }),
    linkCultureHeritage: t({
      en: "Culture & Heritage", zh: "文化与遗产", hi: "संस्कृति और विरासत", es: "Cultura y patrimonio", fr: "Culture et patrimoine", ar: "الثقافة والتراث",
      bn: "সংস্কৃতি ও ঐতিহ্য", pt: "Cultura e patrimônio", ru: "Культура и наследие", ur: "ثقافت اور ورثہ", id: "Budaya & Warisan", de: "Kultur & Erbe",
      ja: "文化と遺産", sw: "Utamaduni na Urithi", ko: "문화 & 유산", it: "Cultura e patrimonio",
    }),
    linkAdventure: t({
      en: "Adventure", zh: "冒险", hi: "साहसिक", es: "Aventura", fr: "Aventure", ar: "مغامرة",
      bn: "রোমাঞ্চ", pt: "Aventura", ru: "Приключения", ur: "مہم جوئی", id: "Petualangan", de: "Abenteuer",
      ja: "アドベンチャー", sw: "Matukio ya Kusisimua", ko: "어드벤처", it: "Avventura",
    }),
    linkFestivals: t({
      en: "Festivals", zh: "节日", hi: "उत्सव", es: "Festivales", fr: "Festivals", ar: "المهرجانات",
      bn: "উৎসব", pt: "Festivais", ru: "Фестивали", ur: "میلے", id: "Festival", de: "Festivals",
      ja: "フェスティバル", sw: "Sherehe", ko: "축제", it: "Festival",
    }),
    linkRestaurantsHotels: t({
      en: "Restaurants & Hotels", zh: "餐厅与酒店", hi: "रेस्तरां और होटल", es: "Restaurantes y hoteles", fr: "Restaurants et hôtels", ar: "المطاعم والفنادق",
      bn: "রেস্তোরাঁ ও হোটেল", pt: "Restaurantes e hotéis", ru: "Рестораны и отели", ur: "ریستوران اور ہوٹل", id: "Restoran & Hotel", de: "Restaurants & Hotels",
      ja: "レストラン＆ホテル", sw: "Migahawa na Hoteli", ko: "레스토랑 & 호텔", it: "Ristoranti e hotel",
    }),
    linkListEvent: t({
      en: "List an Event", zh: "发布活动", hi: "इवेंट सूचीबद्ध करें", es: "Publicar un evento", fr: "Publier un événement", ar: "أضف فعالية",
      bn: "ইভেন্ট তালিকাভুক্ত করুন", pt: "Cadastrar um evento", ru: "Разместить событие", ur: "ایونٹ درج کریں", id: "Daftarkan Acara", de: "Veranstaltung eintragen",
      ja: "イベントを掲載", sw: "Orodhesha Tukio", ko: "이벤트 등록", it: "Pubblica un evento",
    }),
    linkListBusiness: t({
      en: "List a Business", zh: "发布商家", hi: "व्यवसाय सूचीबद्ध करें", es: "Publicar un negocio", fr: "Ajouter une entreprise", ar: "أضف عملاً",
      bn: "ব্যবসা তালিকাভুক্ত করুন", pt: "Cadastrar uma empresa", ru: "Разместить бизнес", ur: "کاروبار درج کریں", id: "Daftarkan Bisnis", de: "Unternehmen eintragen",
      ja: "ビジネスを掲載", sw: "Orodhesha Biashara", ko: "비즈니스 등록", it: "Pubblica un'attività",
    }),
    linkDashboard: t({
      en: "Dashboard", zh: "控制台", hi: "डैशबोर्ड", es: "Panel", fr: "Tableau de bord", ar: "لوحة التحكم",
      bn: "ড্যাশবোর্ড", pt: "Painel", ru: "Панель управления", ur: "ڈیش بورڈ", id: "Dasbor", de: "Dashboard",
      ja: "ダッシュボード", sw: "Dashibodi", ko: "대시보드", it: "Pannello di controllo",
    }),
    linkCreateAccount: t({
      en: "Create Account", zh: "创建账户", hi: "खाता बनाएं", es: "Crear cuenta", fr: "Créer un compte", ar: "إنشاء حساب",
      bn: "অ্যাকাউন্ট তৈরি করুন", pt: "Criar conta", ru: "Создать аккаунт", ur: "اکاؤنٹ بنائیں", id: "Buat Akun", de: "Konto erstellen",
      ja: "アカウント作成", sw: "Fungua Akaunti", ko: "계정 만들기", it: "Crea account",
    }),
    linkSignIn: t({
      en: "Sign In", zh: "登录", hi: "साइन इन करें", es: "Iniciar sesión", fr: "Se connecter", ar: "تسجيل الدخول",
      bn: "সাইন ইন করুন", pt: "Entrar", ru: "Войти", ur: "سائن ان کریں", id: "Masuk", de: "Anmelden",
      ja: "サインイン", sw: "Ingia", ko: "로그인", it: "Accedi",
    }),
    copyrightNote: t({
      en: "All listings are admin-verified before going live.",
      zh: "所有列表在上线前均经过管理员核实。",
      hi: "सभी लिस्टिंग लाइव होने से पहले एडमिन द्वारा सत्यापित की जाती हैं।",
      es: "Todos los anuncios son verificados por un administrador antes de publicarse.",
      fr: "Toutes les annonces sont vérifiées par un administrateur avant leur mise en ligne.",
      ar: "يتم التحقق من جميع القوائم من قبل المسؤول قبل نشرها.",
      bn: "সমস্ত তালিকা লাইভ হওয়ার আগে অ্যাডমিন দ্বারা যাচাই করা হয়।",
      pt: "Todos os anúncios são verificados por um administrador antes de entrarem no ar.",
      ru: "Все объявления проверяются администратором перед публикацией.",
      ur: "تمام فہرستیں لائیو ہونے سے پہلے ایڈمن سے تصدیق شدہ ہوتی ہیں۔",
      id: "Semua listingan diverifikasi admin sebelum tayang.",
      de: "Alle Einträge werden vor der Veröffentlichung von einem Admin geprüft.",
      ja: "すべての掲載情報は公開前に管理者が確認しています。",
      sw: "Orodha zote zinathibitishwa na msimamizi kabla ya kuchapishwa.",
      ko: "모든 등록 정보는 게시 전에 관리자가 확인합니다.",
      it: "Tutti gli annunci vengono verificati da un amministratore prima della pubblicazione.",
    }),
    poweredByNote: t({
      en: "Smart recommendations powered by your interests & location.",
      zh: "智能推荐基于你的兴趣与位置。",
      hi: "स्मार्ट सिफारिशें आपकी रुचियों और स्थान पर आधारित हैं।",
      es: "Recomendaciones inteligentes basadas en tus intereses y ubicación.",
      fr: "Recommandations intelligentes basées sur vos centres d'intérêt et votre position.",
      ar: "توصيات ذكية مبنية على اهتماماتك وموقعك.",
      bn: "আপনার আগ্রহ এবং অবস্থানের উপর ভিত্তি করে স্মার্ট সুপারিশ।",
      pt: "Recomendações inteligentes baseadas nos seus interesses e localização.",
      ru: "Умные рекомендации на основе ваших интересов и местоположения.",
      ur: "آپ کی دلچسپیوں اور مقام کی بنیاد پر ہوشیار تجاویز۔",
      id: "Rekomendasi cerdas berdasarkan minat & lokasi Anda.",
      de: "Intelligente Empfehlungen basierend auf deinen Interessen & deinem Standort.",
      ja: "あなたの興味と位置情報に基づくスマートなおすすめ。",
      sw: "Mapendekezo mahiri kulingana na mapendeleo yako na eneo lako.",
      ko: "관심사와 위치를 기반으로 한 스마트 추천.",
      it: "Consigli intelligenti basati sui tuoi interessi e sulla tua posizione.",
    }),
  },
} satisfies Dictionary;

export default footerContent;
