import { t, type Dictionary } from "intlayer";

const heroContent = {
  key: "hero-video-unit",
  content: {
    eyebrow: t({
      en: "Events · Businesses · Destinations",
      zh: "活动 · 商家 · 目的地",
      hi: "इवेंट्स · व्यवसाय · गंतव्य",
      es: "Eventos · Negocios · Destinos",
      fr: "Événements · Entreprises · Destinations",
      ar: "الفعاليات · الأعمال · الوجهات",
      bn: "ইভেন্ট · ব্যবসা · গন্তব্য",
      pt: "Eventos · Empresas · Destinos",
      ru: "События · Бизнес · Направления",
      ur: "ایونٹس · کاروبار · منزلیں",
      id: "Acara · Bisnis · Destinasi",
      de: "Veranstaltungen · Unternehmen · Reiseziele",
      ja: "イベント・ビジネス・観光地",
      sw: "Matukio · Biashara · Maeneo",
      ko: "이벤트 · 비즈니스 · 여행지",
      it: "Eventi · Attività · Destinazioni",
    }),
    headlineLine1: t({
      en: "Discover what's happening",
      zh: "发现正在发生的事情",
      hi: "जानें क्या हो रहा है",
      es: "Descubre lo que está pasando",
      fr: "Découvrez ce qui se passe",
      ar: "اكتشف ما يحدث",
      bn: "আবিষ্কার করুন কী ঘটছে",
      pt: "Descubra o que está acontecendo",
      ru: "Узнайте, что происходит",
      ur: "دریافت کریں کیا ہو رہا ہے",
      id: "Temukan apa yang sedang terjadi",
      de: "Entdecke, was gerade passiert",
      ja: "今起きていることを発見しよう",
      sw: "Gundua yanayoendelea",
      ko: "지금 무슨 일이 일어나고 있는지 알아보세요",
      it: "Scopri cosa sta succedendo",
    }),
    headlineLine2: t({
      en: "around you — and the world",
      zh: "在你身边 —— 乃至全世界",
      hi: "आपके आसपास — और दुनिया भर में",
      es: "a tu alrededor — y en el mundo",
      fr: "autour de vous — et dans le monde",
      ar: "من حولك — وفي العالم",
      bn: "আপনার আশেপাশে — এবং বিশ্বজুড়ে",
      pt: "ao seu redor — e no mundo",
      ru: "вокруг вас — и по всему миру",
      ur: "آپ کے ارد گرد — اور دنیا بھر میں",
      id: "di sekitar Anda — dan di seluruh dunia",
      de: "in deiner Nähe — und weltweit",
      ja: "あなたの周りで —— そして世界中で",
      sw: "kukuzunguka — na duniani kote",
      ko: "당신 주변에서 — 그리고 전 세계에서",
      it: "intorno a te — e nel mondo",
    }),
    tagline: t({
      en: "Verified events, local businesses, and tourism destinations. Smart recommendations that learn from your interests — the more you explore, the better it gets.",
      zh: "经过验证的活动、本地商家和旅游目的地。智能推荐会根据你的兴趣不断学习——你探索得越多，推荐就越精准。",
      hi: "सत्यापित इवेंट्स, स्थानीय व्यवसाय और पर्यटन स्थल। स्मार्ट सिफारिशें जो आपकी रुचियों से सीखती हैं — जितना अधिक आप खोजेंगे, उतना ही बेहतर होगा।",
      es: "Eventos verificados, negocios locales y destinos turísticos. Recomendaciones inteligentes que aprenden de tus intereses: cuanto más exploras, mejor se vuelve.",
      fr: "Des événements vérifiés, des entreprises locales et des destinations touristiques. Des recommandations intelligentes qui apprennent de vos centres d'intérêt — plus vous explorez, meilleures elles deviennent.",
      ar: "فعاليات موثقة، وأعمال محلية، ووجهات سياحية. توصيات ذكية تتعلم من اهتماماتك — كلما استكشفت أكثر، أصبحت التوصيات أفضل.",
      bn: "যাচাইকৃত ইভেন্ট, স্থানীয় ব্যবসা এবং পর্যটন গন্তব্য। স্মার্ট সুপারিশ যা আপনার আগ্রহ থেকে শেখে — আপনি যত বেশি অন্বেষণ করবেন, তত ভালো হবে।",
      pt: "Eventos verificados, empresas locais e destinos turísticos. Recomendações inteligentes que aprendem com seus interesses — quanto mais você explora, melhor fica.",
      ru: "Проверенные события, местные компании и туристические направления. Умные рекомендации, которые учатся на ваших интересах — чем больше вы исследуете, тем лучше становится сервис.",
      ur: "تصدیق شدہ ایونٹس، مقامی کاروبار اور سیاحتی مقامات۔ ہوشیار تجاویز جو آپ کی دلچسپیوں سے سیکھتی ہیں — جتنا زیادہ آپ دریافت کریں گے، اتنا ہی بہتر ہوگا۔",
      id: "Acara terverifikasi, bisnis lokal, dan destinasi wisata. Rekomendasi cerdas yang belajar dari minat Anda — semakin banyak Anda menjelajah, semakin baik hasilnya.",
      de: "Verifizierte Veranstaltungen, lokale Unternehmen und Reiseziele. Intelligente Empfehlungen, die aus deinen Interessen lernen — je mehr du entdeckst, desto besser wird es.",
      ja: "認証済みのイベント、地元のビジネス、観光地。あなたの興味から学ぶスマートなおすすめ機能 —— 探せば探すほど、精度が上がります。",
      sw: "Matukio yaliyothibitishwa, biashara za karibu, na maeneo ya utalii. Mapendekezo mahiri yanayojifunza kutoka kwa mapendeleo yako — kadiri unavyochunguza zaidi, ndivyo inavyozidi kuwa bora.",
      ko: "검증된 이벤트, 지역 비즈니스, 관광지. 관심사를 학습하는 스마트 추천 — 더 많이 탐색할수록 더 좋아집니다.",
      it: "Eventi verificati, attività locali e destinazioni turistiche. Consigli intelligenti che imparano dai tuoi interessi: più esplori, più diventano precisi.",
    }),
    browseEvents: t({
      en: "Browse events",
      zh: "浏览活动",
      hi: "इवेंट्स देखें",
      es: "Explorar eventos",
      fr: "Parcourir les événements",
      ar: "تصفح الفعاليات",
      bn: "ইভেন্ট ব্রাউজ করুন",
      pt: "Ver eventos",
      ru: "Смотреть события",
      ur: "ایونٹس دیکھیں",
      id: "Jelajahi acara",
      de: "Veranstaltungen entdecken",
      ja: "イベントを見る",
      sw: "Vinjari matukio",
      ko: "이벤트 둘러보기",
      it: "Sfoglia eventi",
    }),
    findBusinesses: t({
      en: "Find businesses",
      zh: "寻找商家",
      hi: "व्यवसाय खोजें",
      es: "Buscar negocios",
      fr: "Trouver des entreprises",
      ar: "ابحث عن الأعمال",
      bn: "ব্যবসা খুঁজুন",
      pt: "Encontrar empresas",
      ru: "Найти бизнес",
      ur: "کاروبار تلاش کریں",
      id: "Temukan bisnis",
      de: "Unternehmen finden",
      ja: "ビジネスを探す",
      sw: "Tafuta biashara",
      ko: "비즈니스 찾기",
      it: "Trova attività",
    }),
    search: t({
      en: "Search",
      zh: "搜索",
      hi: "खोजें",
      es: "Buscar",
      fr: "Rechercher",
      ar: "بحث",
      bn: "অনুসন্ধান",
      pt: "Pesquisar",
      ru: "Поиск",
      ur: "تلاش کریں",
      id: "Cari",
      de: "Suchen",
      ja: "検索",
      sw: "Tafuta",
      ko: "검색",
      it: "Cerca",
    }),
  },
} satisfies Dictionary;

export default heroContent;
